# Generated by Django 3.1.7 on 2021-04-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_notes_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description_todo',
            field=models.TextField(blank=True),
        ),
    ]
