# Generated by Django 3.1.7 on 2021-04-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20210416_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done_todo',
            new_name='important_todo',
        ),
    ]
