# Generated by Django 3.1.7 on 2021-04-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20210417_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='description_notes',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='title_notes',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='user_notes',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='description_todo',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='important_todo',
            new_name='important',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title_todo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='user_todo',
            new_name='user',
        ),
    ]
